language: node_js

node_js:
  - 14.15.1

cache:
  directories:
    - '$HOME/.npm'

install:
  - cd client
  - npm i
  - cd ..
  - cd server
  - npm i

script:
  - cd ..
  - cd client
  - npm run build
